site_name: System Administration
theme_dir: '2600Hz_theme'

pages:
- 'index.md'
- 'Getting Started':
  - 'READ FIRST!' : 'doc/intro/read_me_first.md'
  - 'Introduction' :
    - 'About' : 'doc/intro/about.md'
#     - 'Resources' : 'doc/intro/resources.md'
    - 'Build System' : 'doc/intro/build_system.md'
#     - 'Getting Help': 'doc/intro/get_help.md'
#     - 'Contributing': 'doc/intro/contributing.md'
  - 'Preparation' :
    - 'Requirements' : 'doc/install/minimum_requirements.md'
#     - 'Installation Methods' : 'doc/install/install_overview.md'
#     - 'Zones' : 'doc/install/planning_zones.md'
  - 'Installation' :
#     - 'Downloading' : 'doc/install/downloading.md'
    - 'via CentOS 7' : 'doc/install/install_via_centos7.md'
#     - 'via Cluster Manager' : 'doc/install/install_via_cluster_manager.md'
    - 'via RPM' : 'doc/install/install_via_rpm.md'
#     - 'via Debian' : 'doc/install/install_via_debian.md'
    - 'via ISO' : 'doc/install/install_via_iso.md'
- 'Configuration':
  - 'Quick Start' : 'doc/install/configure_kazoo.md'
  - 'General Concepts':
#     - 'Configuration Documents' : 'doc/config/system_config.md'
  - 'Account Management':
    - 'Manual Creation' : 'doc/config/account_creation.md'
  - 'DNS':
    - 'Core Concepts' : 'doc/config/dns_concepts.md'
  - 'SSL':
    - 'Easy Setup' : 'doc/config/ssl/easy_setup.md'
#     - 'SSL for APIs' : 'doc/config/ssl/for_api.md'
#     - 'SSL for WSS' : 'doc/config/ssl/for_wss.md'
#     - 'SSL for TLS' : 'doc/config/ssl/for_tls.md'
  - 'Limits':
#     - 'Concepts' : 'doc/config/limits/concepts.md'
#     - 'Configuration' : 'doc/config/limits/config.md'
#     - 'Commands' : 'doc/config/limits/commands.md'
- 'Cluster Operation':
#  - 'Monitoring' :
#     - 'Things to Monitor' : 'doc/operation/monitoring.md'
  - 'Security' :
    - 'IPTables' : 'doc/security/iptables.md'
- 'Advanced Concepts':
  - 'API Control':
    - 'Authentication' : 'doc/crossbar/authentication.md'
#  - 'Extending Kazoo':
#     - 'Authorization' : 'doc/extending/authz.md'
- 'Appendix':
#   - 'Advanced-Concepts' : 'doc/intro/advanced-concepts.md'
  - 'Basic-SIPp' : 'doc/config/basic-sipp.md'
#   - 'Build-Own' : 'doc/intro/build-own.md'
  - 'CentOS' : 'doc/install/install_manually_centos.md'
#   - 'Cluster-Design' : 'doc/intro/cluster-design.md'
  - 'Cluster-Health' : 'doc/operation/cluster-health.md'
#   - 'Create-Template' : 'doc/intro/create-template.md'
  - 'Crossbar-API' : 'doc/crossbar/api-design.md'
  - 'Crossbar-Haproxy' : 'doc/crossbar/haproxy.md'
  - 'Crossbar-REST' : 'doc/crossbar/rest-ssl.md'
  - 'DB-Health' : 'doc/config/database-health.md'
  - 'Debian' : 'doc/install/install_manually_debian.md'
  - 'Dedicated-FS' : 'doc/kazoo/dedicated-fs.md'
#   - 'Disable-Servers' : 'doc/intro/disabling-servers.md'
  - 'Distributed-Registration' : 'doc/intro/distributed-reg.md'
  - 'ETS-Persist' : 'doc/operation/ets-persist.md'
  - 'Ecallmgr-Cmd' : 'doc/kazoo/ecallmgr-cmd.md'
#   - 'Email--Config' : 'doc/config/email-templates.md'
  - 'Enable-CNAM' : 'doc/kazoo/enable-cnam.md'
#   - 'Expand-Cluster' : 'doc/intro/expand-cluster.md'
#   - 'G729-Licensing' : 'doc/intro/g729-licensing.md'
  - 'Getting-Started' : 'doc/intro/getting-started.md'
  - 'Global-Resources' : 'doc/config/global-resources.md'
  - 'Happy-Programmer' : 'doc/intro/happy-programmer.md'
#   - 'Home-Page' : 'doc/kazoo/home-page.md'
#   - 'Inbound-Call' : 'doc/intro/inbound-call-issue.md'
  - 'Inbound-Fail' : 'doc/intro/inbound-call-fail.md'
  - 'iSpeech-TTS' : 'doc/config/adding-ispeech-tts.md'
  - 'Jonny5-WhApp' : 'doc/whapp/jonny5.md'
#   - 'Kazoo-CSS' : 'doc/config/css-custom.md'
  - 'Kazoo-Call-Rating' : 'doc/kazoo/call-rating.md'
  - 'Kazoo-Carrier' : 'doc/carrier-numbers/kazoo-carrier.md'
  - 'Kazoo-CarrierModules' : 'doc/config/carrier-modules.md'
#   - 'Kazoo-ClusterGuide' : 'doc/kazoo/cluster-guide.md'
#   - 'Kazoo-Config' : 'doc/config/kazoo-config.md'
  - 'Kazoo-Couch' : 'doc/intro/kazoo-couch.md'
  - 'Kazoo-Debug' : 'doc/kazoo/kazoo-debug.md'
  - 'Kazoo-Media' : 'doc/intro/kazoo-media.md'
#   - 'Kazoo-Number-Manager' : 'doc/carrier-numbers/docs.md'
  - 'Kazoo-Numberlifecycle' : 'doc/carrier-numbers/kazoo-numberlifecycle.md'
  - 'Kazoo-NumbersDocsI' : 'doc/carrier-numbers/kazoo-numberdoc.md'
  - 'Kazoo-OpenSource' : 'doc/kazoo/open-source.md'
  - 'KazooUI-Optimize' : 'doc/kazoo/optimize-kazoo-ui.md'
#   - 'Kazoo-Provider' : 'doc/carrier-numbers/kazoo-provider.md'
  - 'Kazoo-RateEngine' : 'doc/kazoo/rating-engine.md'
  - 'Kazoo-Routing' : 'doc/carrier-numbers/routing.md'
#   - 'Kazoo-SIPFlowchart' : 'doc/kazoo/sip-flowchart.md'
#   - 'Kazoo-ServerMisc' : 'doc/kazoo/kazoo-servermisc.md'
#   - 'Kazoo-ServiceLimits' : 'doc/kazoo/service-limits.md'
  - 'Kazoo-ServicePlans' : 'doc/kazoo/service-plans.md'
#   - 'Kazoo-TDM' : 'doc/kazoo/tdm.md'
  - 'Kazoo-WhApp' : 'doc/whapp/build.md'
#   - 'KazooUI-Misc' : 'doc/kazoo/kazoo-uimisc.md'
  - 'Lineman-Expect' : 'doc/config/lineman-expect.md'
  - 'Lineman-Test' : 'doc/config/lineman-test.md'
#   - 'Load-Failure' : 'doc/intro/load-failure.md'
  - 'Login-NoApps' : 'doc/operation/login-noapps.md'
#   - 'Milliwat-Intro' : 'doc/intro/milliwatt.md'
  - 'Milliwatt-Config' : 'doc/config/milliwatt-config.md'
  - 'Monitor-Maintain' : 'doc/config/monitor-maintain.md'
#   - 'Monster-LoginIssue' : 'doc/monster/login-issues.md'
  - 'Monster-Optimize' : 'doc/monster/optimize-monster.md'
  - 'Number-Lifecycle' : 'doc/intro/number-lifecycle.md'
  - 'Registrar-Design' : 'doc/config/registrar-design.md'
#   - 'Startup-Sequence' : 'doc/intro/startup-sequence.md'
  - 'Store-Forward' : 'doc/intro/storefwd.md'
  - 'Sup-Command' : 'doc/config/sup-command.md'
  - 'iSpeech-TTS' : 'doc/config/adding-ispeech-tts.md'
